# commit to be tagged for the new release
commit = "HEAD"

project_name = "theila"
github_repo = "talos-systems/theila"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

pre_release = true

[notes]

  [notes.intro]

    title = "The First Release"
    description = """\
This is the very first release of the UI for Talos and Sidero.

Theila gets credentials from `~/.kube/config` or from the file defined in `KUBECONFIG`
environment variable.

For each cluster it is possible to get the list of nodes and pods.

If Sidero is deployed then the UI also provides a way to view:
- the list of servers.
- the list of clusters (for any CAPI provider).
- allows getting kubeconfig and talosconfig for each Sidero cluster.

For each node in the cluster it is possible to:
- get the list of services and their health.
- get node logs.
- get performance metrics.
- get each internal service logs (etcd, apid, machined and so on).
- reboot the node.
"""
